In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 안녕하세요^^
## AIVLE 1차 미니프로젝트 '서울시 생활정보 기반 대중교통 수요 분석 ' 과정에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

# 데이터 분석부터 먼저 시작해보겠습니다.
## "구별 업종 등록 데이터" 를 확인해 보도록 하겠습니다

In [ ]:
# 필요 라이브러리부터 설치합니다.
# %pip install pandas seaborn

## 기본전제
* 처음에 제공되는 기본/추가 데이터는 'raw_data' 폴더에 있습니다.

[기본 데이터]
* 1.4 business_type_202401.csv

[데이터 소개]
* 서울 시 구별 등록 업종 상위 10개 데이터(제공 가능한 최신 버전)
    * 택시 운송업 (개인택시 등록자 주거지)
    * 한식일반음식점업
    * 용달 화물자동차 운송업(개인용달 등록자 주거지)
    * 부동산 중개 및 대리업
    * 두발미용업
    * 커피전문점
    * 남녀용 겉옷 및 셔츠 도매업
    * 기타주점업
    * 일반 교과 학원
    * 한식 육류요리 전문점

[변수 소개]
* 다수 업종 상위 1~10

---

# 1.데이터 불러오기
## 모든 미니 프로젝트의 시작은 '데이터 불러오기' 부터라고 할 수 있습니다.
+ KeyPoint : 불러오고자 하는 데이터에 따라 자유롭게 변수로 지정할 수 있다.

###  데이터 프레임을 불러오고 변수로 저장(여기서는 CSV 기준으로 진행)
* csv : pd.read_csv("파일이름. csv")
* txt : pd.read_csv("파일이름. csv", sep="구분자")
* xlsx : pd.read_excel('파일이름.xlsx')
* pickle : pd.read_pickle("파일이름.pkl") <br>
 [참고] pickle은 파이썬의 모든 객체를 파일로 저장할 수 있는 방법으로 DataFrame,List,Dict 등 모든 객체 저장 가능(특히 sklearn라이브러리를 통해 모델을 학습시키고, 저장할 때 많이 사용)

#### [실습문제1] 데이터 로딩
* 'business_type_202401.csv'파일을 'seoul_business' 변수에 저장하고 그 데이터를 확인하세요.
    * 데이터 파일 로딩시 참고 사항
        * 구분자(sep)는 ',' 입니다
        * UTF-8 인코더를 사용해 주세요

In [57]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
import pandas as pd

seoul_business = pd.read_csv('/content/drive/MyDrive/KTaivle/1차미니프로젝트/1.4 business_type_202401.csv',sep=",", encoding = 'UTF-8')

In [3]:
# 데이터 프레임의 Shape을 확인합니다.
seoul_business.shape

(451, 22)

---

# 2.기본 정보 확인 및 클렌징

+ 데이터 클렌징 : 결측치, 이상치 등을 제거하여 데이터 분석 결과가 왜곡 되는 문제를 방지하기 위한 정제 과정

#### [실습문제2] 기본 정보 확인하기
* 'seoul_business' 데이터의 정보를 확인해보세요.
* 'describe', 'info', 'head' 등 전부 활용해 보겠습니다.

In [4]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# info()
seoul_business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 451 entries, 0 to 450
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   자치구           451 non-null    object
 1   동             451 non-null    object
 2   다수업종 상위10     451 non-null    object
 3   다수업종 상위10.1   451 non-null    object
 4   다수업종 상위10.2   451 non-null    object
 5   다수업종 상위10.3   451 non-null    object
 6   다수업종 상위10.4   451 non-null    object
 7   다수업종 상위10.5   451 non-null    object
 8   다수업종 상위10.6   451 non-null    object
 9   다수업종 상위10.7   451 non-null    object
 10  다수업종 상위10.8   451 non-null    object
 11  다수업종 상위10.9   451 non-null    object
 12  다수업종 상위10.10  451 non-null    object
 13  다수업종 상위10.11  451 non-null    object
 14  다수업종 상위10.12  451 non-null    object
 15  다수업종 상위10.13  451 non-null    object
 16  다수업종 상위10.14  451 non-null    object
 17  다수업종 상위10.15  451 non-null    object
 18  다수업종 상위10.16  451 non-null    object
 19  다수업종 상위10.17  451 non-null    object
 20  다수업종 상위10.18  451 non-null    object
 21  다수업종 상위10.19  451 non-null    object
dtypes: object(22)
memory usage: 77.6+ KB

In [5]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# describe()
seoul_business.describe()

,자치구,동,다수업종 상위10,다수업종 상위10.1,다수업종 상위10.2,다수업종 상위10.3,다수업종 상위10.4,다수업종 상위10.5,다수업종 상위10.6,다수업종 상위10.7,...,다수업종 상위10.10,다수업종 상위10.11,다수업종 상위10.12,다수업종 상위10.13,다수업종 상위10.14,다수업종 상위10.15,다수업종 상위10.16,다수업종 상위10.17,다수업종 상위10.18,다수업종 상위10.19
count,451,451,451,451,451,451,451,451,451,451,...,451,451,451,451,451,451,451,451,451,451
unique,27,425,226,280,176,305,177,180,142,205,...,131,239,69,147,127,189,113,222,107,230
top,송파구,소계,71,11,24,104,56,56,40,54,...,13,16,-,-,18,20,4,42,17,45
freq,28,25,7,7,11,6,8,9,11,9,...,18,8,82,82,14,10,15,10,16,9

In [6]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# head()
seoul_business.head()

,자치구,동,다수업종 상위10,다수업종 상위10.1,다수업종 상위10.2,다수업종 상위10.3,다수업종 상위10.4,다수업종 상위10.5,다수업종 상위10.6,다수업종 상위10.7,...,다수업종 상위10.10,다수업종 상위10.11,다수업종 상위10.12,다수업종 상위10.13,다수업종 상위10.14,다수업종 상위10.15,다수업종 상위10.16,다수업종 상위10.17,다수업종 상위10.18,다수업종 상위10.19
0,자치구,동,택시운송업,택시운송업,한식 일반 음식점업,한식 일반 음식점업,용달 화물자동차 운송업,용달 화물자동차 운송업,부동산 중개 및 대리업,부동산 중개 및 대리업,...,커피전문점,커피전문점,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업,기타주점업,기타주점업,일반 교과 학원,일반 교과 학원,한식 육류요리 전문점,한식 육류요리 전문점
1,자치구,동,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
2,합계,합계,"47,176","76,701","29,225","100,183","28,494","29,356","24,013","42,636",...,"16,255","57,322","13,388","51,116","13,339","31,371","11,911","50,773","11,109","44,653"
3,종로구,소계,215,215,"1,548","5,912",618,646,549,889,...,948,"3,613",400,962,537,"1,413",110,382,437,"1,982"
4,종로구,사직동,7,7,230,982,12,12,57,96,...,124,525,2,18,74,177,9,34,45,220

In [7]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# tail()
seoul_business.tail()

,자치구,동,다수업종 상위10,다수업종 상위10.1,다수업종 상위10.2,다수업종 상위10.3,다수업종 상위10.4,다수업종 상위10.5,다수업종 상위10.6,다수업종 상위10.7,...,다수업종 상위10.10,다수업종 상위10.11,다수업종 상위10.12,다수업종 상위10.13,다수업종 상위10.14,다수업종 상위10.15,다수업종 상위10.16,다수업종 상위10.17,다수업종 상위10.18,다수업종 상위10.19
446,강동구,성내3동,120,120,135,390,73,73,104,163,...,54,133,10,86,57,103,66,199,44,164
447,강동구,둔촌2동,117,436,63,249,89,89,61,108,...,34,85,10,788,21,39,35,90,24,101
448,강동구,암사1동,209,372,71,195,153,153,67,107,...,29,59,3,6,47,98,31,67,34,98
449,강동구,천호2동,157,187,152,509,144,151,97,188,...,63,212,4,17,95,268,24,42,69,245
450,강동구,길동,"1,441","1,557",152,436,217,225,146,237,...,71,228,6,126,122,294,39,136,70,224

#### [실습문제3] 데이터 확인 및 처리

* head 와 tail 을 보았을때, 어느 데이터만 가져와야 할지 생각 해 봅시다.
* 두번째 행부터 데이터가 시작된다.

In [58]:
seoul_business.columns = seoul_business.iloc[0]

seoul_business

,자치구,동,택시운송업,택시운송업,한식 일반 음식점업,한식 일반 음식점업,용달 화물자동차 운송업,용달 화물자동차 운송업,부동산 중개 및 대리업,부동산 중개 및 대리업,...,커피전문점,커피전문점,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업,기타주점업,기타주점업,일반 교과 학원,일반 교과 학원,한식 육류요리 전문점,한식 육류요리 전문점
0,자치구,동,택시운송업,택시운송업,한식 일반 음식점업,한식 일반 음식점업,용달 화물자동차 운송업,용달 화물자동차 운송업,부동산 중개 및 대리업,부동산 중개 및 대리업,...,커피전문점,커피전문점,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업,기타주점업,기타주점업,일반 교과 학원,일반 교과 학원,한식 육류요리 전문점,한식 육류요리 전문점
1,자치구,동,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
2,합계,합계,"47,176","76,701","29,225","100,183","28,494","29,356","24,013","42,636",...,"16,255","57,322","13,388","51,116","13,339","31,371","11,911","50,773","11,109","44,653"
3,종로구,소계,215,215,"1,548","5,912",618,646,549,889,...,948,"3,613",400,962,537,"1,413",110,382,437,"1,982"
4,종로구,사직동,7,7,230,982,12,12,57,96,...,124,525,2,18,74,177,9,34,45,220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,강동구,성내3동,120,120,135,390,73,73,104,163,...,54,133,10,86,57,103,66,199,44,164
447,강동구,둔촌2동,117,436,63,249,89,89,61,108,...,34,85,10,788,21,39,35,90,24,101
448,강동구,암사1동,209,372,71,195,153,153,67,107,...,29,59,3,6,47,98,31,67,34,98
449,강동구,천호2동,157,187,152,509,144,151,97,188,...,63,212,4,17,95,268,24,42,69,245
450,강동구,길동,"1,441","1,557",152,436,217,225,146,237,...,71,228,6,126,122,294,39,136,70,224

In [59]:
seoul_business = seoul_business.iloc[1:]
seoul_business

,자치구,동,택시운송업,택시운송업,한식 일반 음식점업,한식 일반 음식점업,용달 화물자동차 운송업,용달 화물자동차 운송업,부동산 중개 및 대리업,부동산 중개 및 대리업,...,커피전문점,커피전문점,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업,기타주점업,기타주점업,일반 교과 학원,일반 교과 학원,한식 육류요리 전문점,한식 육류요리 전문점
1,자치구,동,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
2,합계,합계,"47,176","76,701","29,225","100,183","28,494","29,356","24,013","42,636",...,"16,255","57,322","13,388","51,116","13,339","31,371","11,911","50,773","11,109","44,653"
3,종로구,소계,215,215,"1,548","5,912",618,646,549,889,...,948,"3,613",400,962,537,"1,413",110,382,437,"1,982"
4,종로구,사직동,7,7,230,982,12,12,57,96,...,124,525,2,18,74,177,9,34,45,220
5,종로구,삼청동,5,5,42,145,4,4,9,10,...,66,243,2,3,3,8,-,-,7,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,강동구,성내3동,120,120,135,390,73,73,104,163,...,54,133,10,86,57,103,66,199,44,164
447,강동구,둔촌2동,117,436,63,249,89,89,61,108,...,34,85,10,788,21,39,35,90,24,101
448,강동구,암사1동,209,372,71,195,153,153,67,107,...,29,59,3,6,47,98,31,67,34,98
449,강동구,천호2동,157,187,152,509,144,151,97,188,...,63,212,4,17,95,268,24,42,69,245
450,강동구,길동,"1,441","1,557",152,436,217,225,146,237,...,71,228,6,126,122,294,39,136,70,224

In [60]:
# 필요한 열 선택 (자치구, 동, 그리고 종사자 수에 해당하는 열들만 선택)
selected_columns = ['자치구', '동'] + ['한식 일반 음식점업', '두발미용업', '커피전문점', '기타주점업', '일반 교과 학원', '한식 육류요리 전문점']
selected_data = seoul_business[selected_columns]

# '자치구'와 '동' 열을 기준으로 그룹화하고 각 그룹에서 종사자 수를 합산
grouped_data = selected_data.groupby(['자치구', '동']).sum()

# 결과 확인
print(grouped_data)

0        한식 일반 음식점업 한식 일반 음식점업   두발미용업   두발미용업   커피전문점   커피전문점   기타주점업  \
자치구 동
강남구 개포1동          5         11       5       5       4       6       -
    개포2동         29         67      26      36       9      22       9
    개포4동         56        177      32      54      20      68      10
    논현1동        172        724     110     383     105     433      86
    논현2동        189        823      69     314     144     577      66
...             ...        ...     ...     ...     ...     ...     ...
중랑구 신내1동         55        171      48      63      35     105      24
    신내2동         29        106      33      76      14      43       8
    중화1동         24         57      40      53      14      21       9
    중화2동         90        215      62      84      22      42      66
합계  합계       29,225    100,183  18,080  36,214  16,255  57,322  13,339

0          기타주점업 일반 교과 학원 일반 교과 학원 한식 육류요리 전문점 한식 육류요리 전문점
자치구 동
강남구 개포1동       -        2        8           -           -
    개포2동      18       33       62           9          33
    개포4동      14       14       48          14          42
    논현1동     298        4       20          92         483
    논현2동     217       13       48         102         715
...          ...      ...      ...         ...         ...
중랑구 신내1동      40       46      196          40         157
    신내2동      19       48      195          10          39
    중화1동      14       20       75           9          24
    중화2동     122        4        7          44         136
합계  합계    31,371   11,911   50,773      11,109      44,653

[450 rows x 12 columns]

In [61]:
# 중복되는 행 제거
unique_data = grouped_data.groupby(['자치구']).first()

# 필요한 열 선택
selected_columns = ['한식 일반 음식점업', '두발미용업', '커피전문점', '기타주점업', '일반 교과 학원', '한식 육류요리 전문점']

# 필요한 열의 데이터만 선택
result_data = unique_data[selected_columns]

print(result_data)

0    한식 일반 음식점업 한식 일반 음식점업   두발미용업   두발미용업   커피전문점   커피전문점   기타주점업   기타주점업  \
자치구
강남구           5         11       5       5       4       6       -       -
강동구          20         85      23      35      12      63       1       2
강북구          89        241      85     151      34      98      55      94
강서구         235        898      86     243     154     643     114     327
관악구          84        434      30     104      66     203      75     224
광진구          48        177      34      53      38     125      12      29
구로구          47         87      35      43       3       9      53      75
금천구         300      1,186      51     130     220     791      71     155
노원구         104        314      85     116      77     209      49     110
도봉구         114        250      47      62      25      75      41      82
동대문구         52        164      30      45      24      96      20      39
동작구          92        285      52      98      84     324      38      88
마포구         141        420      70     108      52     129      46     103
서대문구         37         94      14      19       7      38      18      37
서초구          26        121       7      17      21      62       1       3
성동구           9         16      23      35      13      32       6      17
성북구          24         66      37      75      20      76      43      78
송파구          39        164      13      57       8      23       9      14
양천구         116        656      65     328      97     470      44     161
영등포구        130        352      55      87      65     155      78     122
용산구         107        397      19      36      55     199      37     109
은평구          62        185      63      89      26      93      67     169
자치구        사업체수       종사자수    사업체수    종사자수    사업체수    종사자수    사업체수    종사자수
종로구          57        270       8       8      46     133       5       9
중구          172        673      16      61      73     272      45     111
중랑구          36         77      38      42      13      18      15      17
합계       29,225    100,183  18,080  36,214  16,255  57,322  13,339  31,371

0    일반 교과 학원 일반 교과 학원 한식 육류요리 전문점 한식 육류요리 전문점
자치구
강남구         2        8           -           -
강동구        37      109           6          19
강북구        10       57          34         102
강서구        16       30         134         655
관악구         5       10          42         189
광진구        56      266          16          92
구로구         1        1          16          41
금천구         4       18         100         375
노원구        21       42          69         242
도봉구         2       11          49         127
동대문구       26      100          17          45
동작구        35      109          28         100
마포구        46      158          39         124
서대문구        8       17           9          25
서초구         9       27           8          60
성동구        19      102           7          23
성북구        43      194           8          32
송파구         4        8           1           2
양천구       113    1,129          42         297
영등포구        6       17          49         141
용산구         2       11          40         144
은평구        28      108          52         181
자치구      사업체수     종사자수        사업체수        종사자수
종로구         3       10           6          21
중구          -        -          67         272
중랑구        10       19          13          43
합계     11,911   50,773      11,109      44,653

In [75]:
# 4번째 row 삭제
result_data = result_data.drop(result_data.index[-5])
result_data.to_csv('result_data.csv', index=True)

print(result_data)

0    한식 일반 음식점업 한식 일반 음식점업   두발미용업   두발미용업   커피전문점   커피전문점   기타주점업   기타주점업  \
자치구
강남구           5         11       5       5       4       6       -       -
강동구          20         85      23      35      12      63       1       2
강북구          89        241      85     151      34      98      55      94
강서구         235        898      86     243     154     643     114     327
관악구          84        434      30     104      66     203      75     224
광진구          48        177      34      53      38     125      12      29
구로구          47         87      35      43       3       9      53      75
금천구         300      1,186      51     130     220     791      71     155
노원구         104        314      85     116      77     209      49     110
도봉구         114        250      47      62      25      75      41      82
동대문구         52        164      30      45      24      96      20      39
동작구          92        285      52      98      84     324      38      88
마포구         141        420      70     108      52     129      46     103
서대문구         37         94      14      19       7      38      18      37
서초구          26        121       7      17      21      62       1       3
성동구           9         16      23      35      13      32       6      17
성북구          24         66      37      75      20      76      43      78
송파구          39        164      13      57       8      23       9      14
양천구         116        656      65     328      97     470      44     161
영등포구        130        352      55      87      65     155      78     122
종로구          57        270       8       8      46     133       5       9
중구          172        673      16      61      73     272      45     111
중랑구          36         77      38      42      13      18      15      17
합계       29,225    100,183  18,080  36,214  16,255  57,322  13,339  31,371

0    일반 교과 학원 일반 교과 학원 한식 육류요리 전문점 한식 육류요리 전문점  \
자치구
강남구         2        8           -           -
강동구        37      109           6          19
강북구        10       57          34         102
강서구        16       30         134         655
관악구         5       10          42         189
광진구        56      266          16          92
구로구         1        1          16          41
금천구         4       18         100         375
노원구        21       42          69         242
도봉구         2       11          49         127
동대문구       26      100          17          45
동작구        35      109          28         100
마포구        46      158          39         124
서대문구        8       17           9          25
서초구         9       27           8          60
성동구        19      102           7          23
성북구        43      194           8          32
송파구         4        8           1           2
양천구       113    1,129          42         297
영등포구        6       17          49         141
종로구         3       10           6          21
중구          -        -          67         272
중랑구        10       19          13          43
합계     11,911   50,773      11,109      44,653

0                                                    합계
자치구
강남구                                       5115546--28--
강동구                              2085233512631237109619
강북구                         892418515134985594105734102
강서구                   235898862431546431143271630134655
관악구                        8443430104662037522451042189
광진구                         481773453381251229562661692
구로구                                47873543395375111641
금천구                   3001,1865113022079171155418100375
노원구                      104314851167720949110214269242
도봉구                          11425047622575418221149127
동대문구                         52164304524962039261001745
동작구                        9228552988432438883510928100
마포구                     1414207010852129461034615839124
서대문구                              379414197381837817925
서초구                                26121717216213927860
성동구                              9162335133261719102723
성북구                            246637752076437843194832
송파구                                 3916413578239144812
양천구                  1166566532897470441611131,12942297
영등포구                       1303525587651557812261749141
종로구                                57270884613359310621
중구                          17267316617327245111--67272
중랑구                            367738421318151710191343
합계    29,225100,18318,08036,21416,25557,32213,33931,...

In [76]:
import pandas as pd

# 주어진 데이터프레임
data = {
    '한식 일반 음식점업': ['5', '11', '5', '5', '4', '6', '-', '-'],
    '두발미용업': ['20', '85', '23', '35', '12', '63', '1', '2'],
    '커피전문점': ['4', '6', '-', '-'],
    '기타주점업': ['37', '109', '6', '19', '55', '94', '1', '1', '16', '41'],
    '일반 교과 학원': ['2', '8', '-', '-'],
    '한식 육류요리 전문점': ['-', '-', '34', '102', '16', '92', '8', '32'],
    '합계': ['29,225', '100,183', '18,080', '36,214', '16,255', '57,322', '13,339', '31,371']
}

df = pd.DataFrame(data)

# 쉼표(,)와 하이픈(-) 제거 후 데이터 타입을 int로 변환
for column in df.columns:
    df[column] = pd.to_numeric(df[column].astype(str).str.replace('[,-]', ''), errors='coerce')

# 결과 확인
print(df.dtypes)
print(df)

ValueError: All arrays must be of the same length

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# header=1
seoul_business = pd.read_csv('/content/drive/MyDrive/KTaivle/1차미니프로젝트/1.4 business_type_202401.csv', sep=",", encoding = "UTF-8", header=1)

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# DataFrame 출력 시 모든 열을 표시하도록 설정

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# head()

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# '동' 열이 '소계'인 행만을 필터링 (구별 데이터만 필요함)

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# '동' 열 제거

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# head()

In [ ]:
# 해당 데이터프레임을 csv 파일로 저장하세요.

---

# 3.데이터 분석하기
+ KeyPoint : 데이터의 형태를 살펴보고 다양한 분석기법을 통해 모델링에 적합하도록 정제요소를 선별할 수 있다.
  * 데이터들의 패턴 탐색
  * 변수들간의 관계 파악

In [1]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 35 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 1s (7,071 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 121749 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [47]:
# 시각화 한글폰트 설정
import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
sns.set(font="Malgun Gothic",#"NanumGothicCoding",
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')

#### [실습문제4] 데이터 분포 알아보기
* 여러 변수들을 다양한 그래프로 그려보고 인사이트를 도출해보세요.

In [46]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
import matplotlib.pyplot as plt

# 결과 데이터에서 필요한 부분만 추출
plot_data = result_data[['한식 일반 음식점업', '두발미용업', '커피전문점', '기타주점업', '일반 교과 학원', '한식 육류요리 전문점']]

# 데이터를 정수형으로 변환
plot_data = plot_data.astype(int)

# 막대 그래프 그리기
plot_data.plot(kind='bar', stacked=True, figsize=(12, 8))
plt.title('각 자치구의 종사자 수')
plt.xlabel('자치구')
plt.ylabel('종사자 수')
plt.legend(title='업종')
plt.show()

ValueError: invalid literal for int() with base 10: '사업체수'

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [ ]:
# 위 차트를 통해 알게된 사실을 정리해봅시다.
# 1.
# 2.
# 3.